apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-wrapper
  labels:
    name: zabbix-wrapper
spec:
  replicas: 1
  selector:
    name: zabbix-wrapper
  template:
    metadata:
      labels:
        name: zabbix-wrapper
    spec:
      containers:
      - name: zabbix-wrapper
        image: michelegrandolfo/zabbix-wrapper:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /monitoring
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 5
